id: bash_extract_names
learningObjectives: 
- Manipulating strings and cutting out parts of a file
hints:
- Make sure the first name comes before the last name, maybe there is a command to flip them?
- It's easier to see the result when you et rid of the text you don't actually need
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Ok, ok. Four spies is an escalation of hostilities. Can you get me their names? First name + last name, please!"
        delay: 1500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - "Brad Pertrew"
            - "Amjad Halil"
            - "Hatake Ken"
            - "Elisabeth Perl"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "That's great, ${user.nickname}. We'll take it from here." 
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "I don't recognize these from our counter-intelligence lists. Only first names and last names, please."
              delay: 2500
